<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="56077" started-at="2017-03-03T06:28:18Z" finished-at="2017-03-03T06:29:14Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="56077" started-at="2017-03-03T06:28:18Z" finished-at="2017-03-03T06:29:14Z">
      <class name="Hazards.PatientIdentificationErrorTest">
        <test-method status="PASS" signature="preTest()[pri:0, instance:Hazards.PatientIdentificationErrorTest@341b80b2]" name="preTest" is-config="true" duration-ms="468" started-at="2017-03-03T11:58:18Z" finished-at="2017-03-03T11:58:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preTest -->
        <test-method status="PASS" signature="preExecutionTest()[pri:0, instance:Hazards.PatientIdentificationErrorTest@341b80b2]" name="preExecutionTest" is-config="true" duration-ms="18308" started-at="2017-03-03T11:58:18Z" finished-at="2017-03-03T11:58:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preExecutionTest -->
        <test-method status="FAIL" signature="patientIdentficationErrorTest()[pri:0, instance:Hazards.PatientIdentificationErrorTest@341b80b2]" name="patientIdentficationErrorTest" duration-ms="34287" started-at="2017-03-03T11:58:37Z" finished-at="2017-03-03T11:59:11Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at Hazards.PatientIdentificationErrorTest.patientIdentficationErrorTest(PatientIdentificationErrorTest.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- patientIdentficationErrorTest -->
        <test-method status="PASS" signature="ITestResult(org.testng.ITestResult)[pri:0, instance:Hazards.PatientIdentificationErrorTest@341b80b2]" name="ITestResult" is-config="true" duration-ms="2970" started-at="2017-03-03T11:59:11Z" finished-at="2017-03-03T11:59:14Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=patientIdentficationErrorTest status=FAILURE method=PatientIdentificationErrorTest.patientIdentficationErrorTest()[pri:0, instance:Hazards.PatientIdentificationErrorTest@341b80b2] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ITestResult -->
        <test-method status="PASS" signature="postExecutionTest()[pri:0, instance:Hazards.PatientIdentificationErrorTest@341b80b2]" name="postExecutionTest" is-config="true" duration-ms="0" started-at="2017-03-03T11:59:14Z" finished-at="2017-03-03T11:59:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postExecutionTest -->
      </class> <!-- Hazards.PatientIdentificationErrorTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
